### ISSUE TITLE
Could not evaluate: undefined method `tags' for Net_share[Tes tShare3]

### ISSUE THREAD

**Issue by aarismendi** [simondean/puppet-net_share#3]
```
Notice: /Stage[main]/Andy::Test/Net_share[TestShare3]/permissions: permissions changed ['EXAMPLE\Service
 Users,full', 'BUILTIN\Administrators,full'] to 'EXAMPLE\Service Users,full Administrators,full'
Error: /Stage[main]/Andy::Test/Net_share[TestShare3]: Could not evaluate: undefined method `tags' for Net_share[Tes
tShare3](provider=net_share):Puppet::Type::Net_share::ProviderNet_share
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:317:in `source='
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:248:in `initialize'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:84:in `new'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:84:in `create'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:98:in `block (2 levels) in logmethods'
C:/ProgramData/PuppetLabs/puppet/var/lib/puppet/provider/net_share/net_share.rb:46:in `flush'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/type.rb:977:in `flush'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction/resource_harness.rb:24:in `evaluate'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:174:in `apply'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:187:in `eval_resource'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:117:in `call'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:117:in `block (2 levels) in evaluate'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:327:in `block in thinmark'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:326:in `thinmark'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:117:in `block in evaluate'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction.rb:108:in `evaluate'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:164:in `block in apply'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/log.rb:149:in `with_destination'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/transaction/report.rb:108:in `as_logging_destination'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/resource/catalog.rb:163:in `apply'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:125:in `block in apply_catalog'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:161:in `block in benchmark'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:160:in `benchmark'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:124:in `apply_catalog'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/configurer.rb:192:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:44:in `block (4 levels) in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent/locker.rb:20:in `lock'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:44:in `block (3 levels) in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:114:in `with_client'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:41:in `block (2 levels) in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:79:in `run_in_fork'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:40:in `block in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:179:in `call'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:179:in `controlled_run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/agent.rb:38:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application/agent.rb:355:in `onetime'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application/agent.rb:321:in `run_command'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:364:in `block (2 levels) in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:470:in `plugin_hook'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:364:in `block in run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:478:in `exit_on_fail'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/application.rb:364:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:137:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/lib/puppet/util/command_line.rb:91:in `execute'
C:/Program Files (x86)/Puppet Labs/Puppet/puppet/bin/puppet:4:in `<main>'
```

**Comment by ruckc** [comment]
This is being thrown in puppet proper, at 
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/log.rb#L322 from the "info" line in the provider.  Somehow the Puppet::Util::Log is having an issue instantiating the log message as whatever the source variable on the object "is", it doesn't have a tags method, even though it has a "path"

**Comment by helenp1983** [comment]
i have the same issue,  i see the error below, if one of the accounts is manullay removed from the share permissions. ( Puppet 3.4.2)

Error: /Stage[main]/Puppetlabs_acl::Net_webserver_acl/Net_share[Repositories]: C
ould not evaluate: undefined method `tags' for Net_share[Repositories](provider=
net_share):Puppet::Type::Net_share::ProviderNet_share

is there a fix ?

**Comment by ben-taylor** [comment]
I just deleted line 46 in lib/puppet/provider/net_share/net_share.rb which has "fixed" the problem for us, not the best solution but it works. It looks like a statement that was left in there from testing.
